model_input:                timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_speed  
model_output:               meter_reading 
input_dir:                  Data/test_icpe_v2
n_steps:                    3
n_features:                 3
conv_filters:               64
conv_kernel_size:           2
pool_size:                  2
hidden_units:               50
epochs:                     10
batch_size:                 72
verbose:                    1
