model_input:                delivery_perc,perc_of_active_connections,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc
model_output:               annual_consume
input_dir:                  Data/DUTCH-ENERGY/endinetGAS
n_steps:                    4
n_features:                 12
conv_filters:               32
conv_kernel_size:           2
pool_size:                  2
hidden_units:               50
epochs:                     10
batch_size:                 8
verbose:                    1
