model_input:                N_urgent,urgent,OrderA,OrderB,OrderC,FSector,TrafficOrder,B1,B2,B3
model_output:               TOrders
input_dir:                  Data/DAILY_FORECASTING
n_steps:                    4
n_features:                 12
conv_filters:               32
conv_kernel_size:           2
pool_size:                  2
hidden_units:               50
epochs:                     10
batch_size:                 8
verbose:                    1
