model_input:                air_temperature,wind_speed,dew_temperature
model_output:               meter_reading
input_dir_train:            Data/ASHRAE/ashrae/results/train/
input_dir_test:             Data/ASHRAE/ashrae/results/test/
output_dir:                 Data/ASHRAE/ashrae/results/
n_steps:                    4
n_features:                 12
conv_filters:               32
conv_kernel_size:           2
pool_size:                  2
hidden_units:               50
epochs:                     10
batch_size:                 8
verbose:                    1
