fields_include: air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,meter_reading
input_dir: Data/ASHRAE/ashrae/results/train/
alg_fs: visualization