model_input:                per_F_Sector ,per_traffic ,per_B1 ,per_B2 ,per_B3 ,per_T_Reg ,per_Resto
model_output:               TOrders
input_dir_train:            Data/DAILY_FORECASTING/train/
input_dir_test:             Data/DAILY_FORECASTING/test/
output_dir:                 Data/DAILY_FORECASTING/result/lstm/
n_steps:                    2
hidden_units:               10
epochs:                     10
batch_size:                 64
verbose:                    1
