model_input:                air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
model_output:               meter_reading
input_dir_train:            Data/Ashrae/results/train
input_dir_test:             Data/Ashrae/results/test
n_steps:                    2
hidden_units:               10
epochs:                     10
batch_size:                 64
verbose:                    1
