model_input:                air_temperature,wind_speed,dew_temperature
model_output:               meter_reading
input_dir_train:            Data/ASHRAE/ashrae/results/train/
input_dir_test:             Data/ASHRAE/ashrae/results/test/
output_dir:                 Data/ASHRAE/ashrae/results/
n_steps:                    2
hidden_units:               10
epochs:                     10
batch_size:                 64
verbose:                    1
