model_input:                X1,X2,X3,X4,X5,X6,X7,X8,Y1
model_output:               Y2
input_dir:                  Data/ENB2012_data
n_steps:                    3
hidden_units:               50
epochs:                     10
batch_size:                 72
verbose:                    1
