model_input:                air_temperature,wind_speed,dew_temperature
model_output:               meter_reading
input_dir_train:            Data/ASHRAE/ashrae/results/train/
input_dir_test:             Data/ASHRAE/ashrae/results/test/
output_dir:                 Data/ASHRAE/ashrae/results/
n_steps:                    1
hidden_units:               32
epochs:                     10
batch_size:                 32
verbose:                    1
