fields_include: num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc
q1: 0.25
q3: 0.75
alg_outliers: visualization
input_dir:  Data/DUTCH-ENERGY/endinetGAS
