date_init: None
date_end:  None
fields_include: None
#path_data: Data/ASHRAE/ashrae/working-data/train.csv
group_by_parent: SystemCodeNumber
type_dataset: train
file_input: Data/PARKING/working-data/parking.csv
output_dir: Data/PARKING/result/train/
