date_init: None
date_end:  None
fields_include: None
path_data: Data/ASHRAE/ashrae/working-data/train.csv
group_by_parent: site_id,meter
output_dir: Data/ASHRAE/ashrae/results/train
type_dataset: 'train'
