model_input:                X1,X2,X3,X4,X5,X6,X7,X8,Y1
model_output:               Y2
input_dir:                  Data/ENB2012_data
n_estimators:               100
criterion:                  mse
max_depth:                  5
min_samples_split:          2
min_samples_leaf:           1
min_weight_fraction_leaf:   0.0
max_features:               auto
max_leaf_nodes:             10
min_impurity_decrease:      0.0
bootstrap:                  True
oob_score:                  False
n_jobs:                     -1
random_state:               0
warm_start:                 False
ccp_alpha:                  0.0
max_samples:                None
figure:                     False
verbose:                    1
n_splits:                   5