model_input:                per_F_Sector ,per_traffic ,per_B1 ,per_B2 ,per_B3 ,per_T_Reg ,per_Resto
model_output:               TOrders
input_dir_train:            Data/DAILY_FORECASTING/train/
input_dir_test:             Data/DAILY_FORECASTING/test/
output_dir:                 Data/DAILY_FORECASTING/result/rf_regression/
n_estimators:               100
criterion:                  mse
max_depth:                  5
min_samples_split:          2
min_samples_leaf:           1
min_weight_fraction_leaf:   0.0
max_features:               auto
max_leaf_nodes:             10
min_impurity_decrease:      0.0
bootstrap:                  True
oob_score:                  False
n_jobs:                     -1
random_state:               0
warm_start:                 False
ccp_alpha:                  0.0
max_samples:                None
figure:                     False
verbose:                    1
n_splits:                   20