model_input:                N_urgent,urgent,OrderA,OrderB,OrderC,FSector,TrafficOrder,B1,B2,B3
model_output:               TOrders
input_dir:                  Data/DAILY_FORECASTING
n_estimators:               100
criterion:                  mse
max_depth:                  5
min_samples_split:          2
min_samples_leaf:           1
min_weight_fraction_leaf:   0.0
max_features:               auto
max_leaf_nodes:             10
min_impurity_decrease:      0.0
bootstrap:                  True
oob_score:                  False
n_jobs:                     -1
random_state:               0
warm_start:                 False
ccp_alpha:                  0.0
max_samples:                None
figure:                     False
verbose:                    1
n_splits:                   5