model_input:                delivery_perc,perc_of_active_connections,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc
model_output:               annual_consume
input_dir:                  Data/DUTCH-ENERGY/endinetGAS
n_splits:                   10
objective:                  reg:squarederror
