model_input:                X1,X2,X3,X4,X5,X6,X7,X8,Y1
model_output:               Y2
input_dir:                  Data/ENB2012_data
n_splits:                   10
objective:                  reg:squarederror
